### ISSUE TITLE
Valid Concern to not use xz ?

### ISSUE THREAD

**Issue by gcstang** [ulikunitz/xz#21]
While researching xz as a storage medium I came across this article.

https://www.nongnu.org/lzip/xz_inadequate.html

Is what they've outlined on this page a valid concern and we shouldn't be using xz?

**Comment by ulikunitz** [comment]
While I share a lot of the observations (complex format, unclear padding rules, LZMA2 format undocumented), I don't share all the conclusions particularly about the severity of bit errors in the headers. If your archiving system doesn't protect you from bit errors then you shouldn't store compressed data on it. In practical terms a bit error in a compressed file will affect all data following it. The exception are parallel compressed files, where unavoidable dictionary resets provide synchronization points. The parallel-compressed segments could be quite large (>= 8 MiB); compare that to an uncompressed UTF-8 file, where every code point is a synchronization point.

If xz is used for archiving purposes, I recommend to use it without any additional filters and use the SHA-256 checksum, since it protects also the length of the data stream. CRC-32 and CRC-64 lack this capability.

**Comment by gcstang** [comment]
@ulikunitz thank you very much for your response.
Does your project by default support what you recommend?

**Comment by ulikunitz** [comment]
I don't support any additional filters, but the default is the CRC64 checksum. You would need a WriterConfig that sets the CheckSum field to SHA256.

**Comment by gcstang** [comment]
@ulikunitz ok, thank you
